# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scheduler_to_trainer_pb2 as scheduler__to__trainer__pb2


class SchedulerToTrainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryStats = channel.unary_unary(
                '/SchedulerToTrainer/QueryStats',
                request_serializer=scheduler__to__trainer__pb2.QueryStatsRequest.SerializeToString,
                response_deserializer=scheduler__to__trainer__pb2.QueryStatsResponse.FromString,
                )


class SchedulerToTrainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerToTrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryStats': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryStats,
                    request_deserializer=scheduler__to__trainer__pb2.QueryStatsRequest.FromString,
                    response_serializer=scheduler__to__trainer__pb2.QueryStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SchedulerToTrainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchedulerToTrainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SchedulerToTrainer/QueryStats',
            scheduler__to__trainer__pb2.QueryStatsRequest.SerializeToString,
            scheduler__to__trainer__pb2.QueryStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
