# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import trainer_to_scheduler_pb2 as trainer__to__scheduler__pb2


class TrainerToSchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTrainer = channel.unary_unary(
                '/TrainerToScheduler/RegisterTrainer',
                request_serializer=trainer__to__scheduler__pb2.RegisterTrainerRequest.SerializeToString,
                response_deserializer=trainer__to__scheduler__pb2.RegisterTrainerResponse.FromString,
                )
        self.ReportStats = channel.unary_unary(
                '/TrainerToScheduler/ReportStats',
                request_serializer=trainer__to__scheduler__pb2.ReportStatsRequest.SerializeToString,
                response_deserializer=trainer__to__scheduler__pb2.ReportStatsResponse.FromString,
                )


class TrainerToSchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterTrainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerToSchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTrainer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTrainer,
                    request_deserializer=trainer__to__scheduler__pb2.RegisterTrainerRequest.FromString,
                    response_serializer=trainer__to__scheduler__pb2.RegisterTrainerResponse.SerializeToString,
            ),
            'ReportStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStats,
                    request_deserializer=trainer__to__scheduler__pb2.ReportStatsRequest.FromString,
                    response_serializer=trainer__to__scheduler__pb2.ReportStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TrainerToScheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainerToScheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterTrainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainerToScheduler/RegisterTrainer',
            trainer__to__scheduler__pb2.RegisterTrainerRequest.SerializeToString,
            trainer__to__scheduler__pb2.RegisterTrainerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainerToScheduler/ReportStats',
            trainer__to__scheduler__pb2.ReportStatsRequest.SerializeToString,
            trainer__to__scheduler__pb2.ReportStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
